version: "3.8"

services:
  backend:
    build: .
    container_name: pujalibre-backend
    ports:
      - "3000:3000"
    volumes:
      - "D:/Proyecto pujalibre/pujalibre-backend:/app"
    working_dir: /app
    command: npm run start
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: pujalibre-db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: pujalibre
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
